name: Build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nixosConfigurations.tower.config.system.build.vm --no-update-lock-file --option accept-flake-config true
      env:
        NIXPKGS_ALLOW_UNFREE: 1
