name: Check
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix config show
    - shell: nix shell github:NixOS/nixpkgs/nixos-unstable#yq github:NixOS/nixpkgs/nixos-unstable#bat
      run: nix flake info --json | yq --yaml-output --yaml-output-grammar-version 1.2 | bat --language yaml --paging never --decorations never
    - run: nix flake show
    - run: nix flake check --verbose
    - run: nix eval --impure --json --expr '(builtins.getFlake (toString ./.)).outputs.nixosConfigurations.tower.config.system.nixos'
