name: Check
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake show --verbose --verbose
    - run: nix eval --impure --expr '(builtins.getFlake (toString ./.)).outputs.nixosConfigurations.tower.config.system.build.toplevel'
