name: Check
on:
  push:
    branches: [main]
  pull_request_target: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix config show
    - shell: nix shell --quiet github:NixOS/nixpkgs/nixos-unstable#yq github:NixOS/nixpkgs/nixos-unstable#bat --command bash -o errexit -o pipefail -o nounset -o xtrace {0}
      run: nix flake metadata --json | yq --yaml-output --yaml-output-grammar-version 1.2 | bat --language yaml --pager '' --plain --force-colorization
    - run: nix flake show
    - run: nix flake check --verbose --show-trace
    - run: nix eval --impure --json --expr '(builtins.getFlake (toString ./.)).outputs.nixosConfigurations.tower.config.system.nixos'
